depends:
  readxl:
    repo: CRAN
    version: 1.0.0
  yaml:
    repo: CRAN
    version: 2.1.14
  dplyr:
    repo: CRAN
    version: 0.7.2
fetch.args:
  sheet: "SUMMARY_wRanks"
filter.args:
  min.samples: 400
