depends:
  aws.s3:
    repo: CRAN
    version: 0.3.3
  aws.signature:
    repo: CRAN
    version: 0.3.5
  yaml:
    repo: CRAN
    version: 2.1.14
fetch.args:
  s3Profile: 'default'
  s3Path: 'MMSD'
  bucket: 'ds-pipeline'
