depends:
  readxl:
    repo: CRAN
    version: 1.0.0
  tidyr:
    repo: CRAN
    version: 0.6.3
  yaml:
    repo: CRAN
    version: 2.1.14
  stringr:
    repo: CRAN
    version: 1.2.0
  dplyr:
    repo: CRAN
    version: 0.7.2
  data.table:
    repo: CRAN
    version: 1.10.4
fetch.args:
  path: "1_get_raw_data/out"
  file.data: "USGS_WQ_DATA_02-16.xlsx"
save.args:
  save.path: "2_clean_sample/out"
  save.file: "sample_data.rds"
