depends:
  EGRET:
    repo: CRAN
    version: 	2.6.0
  dplyr:
    repo: CRAN
    version: 0.7.2
  yaml:
    repo: CRAN
    version: 2.1.14
fetch.args:
  data.path: "5_merge/out"
  progress.file: "progress.csv"
  site.path: "3_filter/out"
  site.file: "summary_sites.rds"
explore.args:
  path: "6_model/doc"
  graph: "model_check.pdf"
log.args:
  path: "6_model/log"
  file: "progress.csv"
save.args:
  path: "6_model/out"

