depends:
  EGRET:
    repo: CRAN
    version: 	2.6.0
  dplyr:
    repo: CRAN
    version: 0.7.2
  yaml:
    repo: CRAN
    version: 2.1.14
fetch.args:
  data.path: "3_merge/out"
  progress.file: "progress.csv"
  site.path: "2a_filter/out"
  site.file: "summary_sites.rds"
save.args:
  save.path: "4_model/out"
  save.graph: "model_check.pdf"
  save.file: "progress.csv"
