depends:
  readxl:
    repo: CRAN
    version: 1.0.0
  yaml:
    repo: CRAN
    version: 2.1.14
  dplyr:
    repo: CRAN
    version: 0.7.2
fetch.args:
  path: "2_clean_sample/out"
  site.path: "1_get_raw_data/out"
  file.data: "sample_data.rds"
  site.data: "SampleGanttCharts_wRanks.xlsx"
  sheet: "SUMMARY_wRanks"
filter.args:
  min.samples: 400
save.args:
  save.path: "3_filter/out"
  save.flow: "summary_flow.rds"
  save.site: "summary_sites.rds"
