depends:
  aws.s3:
    repo: CRAN
    version: 0.3.3
  aws.signature:
    repo: CRAN
    version: 0.3.5
  yaml:
    repo: CRAN
    version: 2.1.14
fetch.args:
  s3Profile: 'default'
  s3Path: 'MMSD'
  bucket: 'ds-pipeline'
  file.data.summary: "USGS_WQ_DATA_02-16.xlsx"
save.args:
  save.path: "1_get_raw_data/out"
